{% set name = "pyaedt" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyaedt-{{ version }}.tar.gz
  sha256: 488f467270e4fcc0fbf6e935675bbdd1171f46beac6c8636be8140c99403884e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - mono  # [linux]
    - dotnet-aspnetcore ==3.1.23  # [linux]

  host:
    - pip
    - python
    - flit-core >=3.2,<4

  run:
    - python
    - mono  # [linux]
    - defusedxml
    - dotnet-aspnetcore ==3.1.23  # [linux]
    - cffi ==1.16.0  # [linux]
    - pywin32 >=303  # [win]
    - pythonnet ==3.0.3
    - rpyc ==5.0.1
    - pyvista >=0.34.1
    - numpy
    - matplotlib-base
    - psutil
    - pandas
    - jsonschema
    - pyyaml
    - tomli
    - tomli-w
    - grpcio >=1.50.0,<1.71

test:
  imports:
    - pyaedt

about:
  home: https://pypi.org/project/pyaedt/
  summary: Higher-Level Pythonic Ansys Electronics Desktop Framework
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
  doc_url: https://aedt.docs.pyansys.com/
  dev_url: https://github.com/pyansys/pyaedt

extra:
  recipe-maintainers:
    - SMoraisAnsys
    - MaxJPRey
    - maxcapodi78
    - Samuelopez-ansys
