{% set name = "pyaedt" %}
{% set version = "0.6.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyaedt-{{ version }}.tar.gz
  sha256: e1889ac4e8a67974d41cae55367a954b2042fcfb110f597efabdb1c19c7677d7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - mono  # [linux]
    - dotnet-aspnetcore ==3.1.23  # [linux]

  host:
    - pip
    - python

  run:
    - python
    - mono  # [linux]
    - dotnet-aspnetcore ==3.1.23  # [linux]
    - cffi ==1.15.0  # [linux]
    - pywin32 >=303  # [win]
    - pythonnet ==3.0.0.post1
    - rpyc ==5.0.1
    - pyvista >=0.34.1
    - numpy
    - matplotlib-base
    - psutil
    - pandas

test:
  imports:
    - pyaedt

about:
  home: https://pypi.org/project/pyaedt/
  summary: Higher-Level Pythonic Ansys Electronics Desktop Framework
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - testenv/Lib/site-packages/idna-3.4.dist-info/LICENSE.md
    - testenv/Lib/site-packages/scipy/fft/_pocketfft/LICENSE.md
    - testenv/Lib/site-packages/traitlets-5.5.0.dist-info/licenses/COPYING.md

extra:
  recipe-maintainers:
    - MaxJPRey
    - maxcapodi78
    - Samuelopez-ansys
