{% set name = "pyaedt" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyaedt-{{ version }}.tar.gz
  sha256: 95fa8059cfe5b1ad53a6fbd86a61466a15303c857c7ac96372071336da5183f9

build:
  skip: true  # [osx or py<310]
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - mono  # [linux]
    - dotnet-sdk ~=7.0  # [linux]

  host:
    - pip
    - python
    - setuptools

  run:
    - python
    # Direct dependencies
    - ansys-tools-common
    - defusedxml >=0.7,<8.0
    - grpcio >=1.50.0,<1.81
    - jsonschema
    - numpy >=1.20.0,<2.3
    - psutil >=6.0.0
    - pydantic >=2.6.4,<2.14
    - pyyaml
    - pyedb ==0.74.0
    - tomli
    - tomli-w
    # NOTE: Optional dependencies (not strictly required, but commonly used)
    - openpyxl >=3.1.0,<3.3
    - pandas >=1.1.0,<2.4
    - fast-simplification >=0.1.7
    - scikit-rf >=0.30.0,<1.12
    - rpyc >=6.0.0,<6.1
    - requests
    # NOTE: Graphics dependencies (pyvista[io] is explicity list below)
    - ansys-tools-visualization-interface
    # pyvista[io] extra (conda has no extras syntax)
    - pyvista >=0.38.0,<0.48
    - imageio
    - meshio >=5.2
    # 
    - matplotlib-base
    - vtk >=9.0,<9.7
    - fpdf2
    - pillow
    # NOTE: .NET related dependencies
    - mono                  # [linux]
    - dotnet-runtime ~=7.0  # [linux]
    - cffi >=1.16.0,<2.1    # [linux]
    - ansys-pythonnet >=3.1.0rc3
    - pywin32 >=303         # [win]

test:
  imports:
    - ansys.aedt.core

about:
  home: https://pypi.org/project/pyaedt/
  summary: Higher-Level Pythonic Ansys Electronics Desktop Framework
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
  doc_url: https://aedt.docs.pyansys.com/
  dev_url: https://github.com/pyansys/pyaedt

extra:
  recipe-maintainers:
    - SMoraisAnsys
    - MaxJPRey
    - maxcapodi78
    - Samuelopez-ansys
