{% set name = "pyaedt" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyaedt-{{ version }}.tar.gz
  sha256: 518aebad78b6424a5015bced42b899852f1a243eadb7a9c9261320c3d3d6c8bb

build:
  skip: true  # [osx or py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - mono  # [linux]
    - dotnet-aspnetcore ==3.1.23  # [linux]

  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - mono  # [linux]
    - defusedxml
    - dotnet-aspnetcore ==3.1.23  # [linux]
    - cffi >=1.16.0  # [linux]
    - pywin32 >=303  # [win]
    - pythonnet >=3.0.3
    - rpyc >=5.0.1
    - pyvista >=0.34.1
    - numpy
    - matplotlib-base
    - psutil
    - pandas
    - jsonschema
    - pyyaml
    - tomli
    - tomli-w
    - grpcio >=1.50.0,<1.76
    - fpdf2
    - pydantic
    # NOTE: Adding scikit-rf to the requirements until v0.25.1 is out.
    # See https://github.com/ansys/pyaedt/pull/7255 for more informations
    - scikit-rf

test:
  imports:
    - ansys.aedt.core

about:
  home: https://pypi.org/project/pyaedt/
  summary: Higher-Level Pythonic Ansys Electronics Desktop Framework
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
  doc_url: https://aedt.docs.pyansys.com/
  dev_url: https://github.com/pyansys/pyaedt

extra:
  recipe-maintainers:
    - SMoraisAnsys
    - MaxJPRey
    - maxcapodi78
    - Samuelopez-ansys
